# Generated by Django 5.1.5 on 2025-02-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_schedule_visit_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_time',
        ),
    ]
