# Generated by Django 5.1.5 on 2025-02-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_remove_visit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='med.schedule'),
        ),
    ]
