# Generated by Django 5.1.5 on 2025-02-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_alter_schedule_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
    ]
