# Generated by Django 5.1.5 on 2025-02-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_remove_visit_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'new'), ('READ', 'reading'), ('ARCH', 'archived')], default='NEW', max_length=4)),
                ('notification_type', models.CharField(choices=[('NEW_VISIT', 'new visit'), ('CANCEL', 'visit cancelled'), ('OTHER', 'other')], default='OTHER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notification', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
